### ISSUE TITLE
page_langs: Error Call to a member function lang() on null

### ISSUE THREAD

**Issue by ArcDee** [marghoobsuleman/hashtagcms#19]
Hello,

After adding a page, I got following error:

1)
Error Call to a member function lang() on null
https://domain.com/admin/page/store

MarghoobSuleman\HashtagCms\Http\Controllers\Admin\BaseAdminController::saveAllData
vendor/marghoobsuleman/hashtagcms/src/Core/Traits/Admin/AdminCrud.php:307

In the Debug Query, it showed (copied here, only relevant):
    select
      `langs`.*,
      `lang_site`.`site_id` as `pivot_site_id`,
      `lang_site`.`lang_id` as `pivot_lang_id`
    from
      `langs`
      inner join `lang_site` on `langs`.`id` = `lang_site`.`lang_id`
    where
      `lang_site`.`site_id` in (1)

Connection name
    mysql

2)
ErrorException
Undefined array key "title" (View: /xxx/public_html/hashtagcms/vendor/marghoobsuleman/hashtagcms/resources/views/be/default/page/addedit.blade.php)

3)

I have manually added (phpmyadmin) a record in the table page_langs manually.
It worked and does not crash any more. Thereafter, I have not added any further page.

**Comment by marghoobsuleman** [comment]
Multisite has some issues. I am working on it. I will fix it by the weekend.

**Comment by ArcDee** [comment]
Hello Marghoob,

It appears that I am the first user of this marvellous HashtagCMS, who has actually tested in many areas further. Others (140+ users) did not reach this point. Therefore, certain areas have minor bugs in it. This happens always and it part of the open source. I am not surprised at all that a minor modification is required to be done.

After understanding the entire logic of many areas you have poured into your HashtagCMS, I can only say that this is so clever. 

Mentioning again, HashtagCMS is one of the best CMS on Laravel I have found.

I assume that it will become one of the best CMS in the world, for which you have the credit for this extraordinary contribution. 

My sincere respect to you for your work as an excellent programmer.

Here, I would like to suggest you to release a next version 1.4-beta of HashtagCMS and tag in the name of this release to include the term beta. Here, you could add some new features too.

I suggest that you release the HashtagCMS as multi language by default.

I am willing to offer you translation in German. I can also help you with docs in English.

A release with beta versions of HashtagCMS may give a clear signal to  all users, that 1.3 should not be installed. I will test every area after you release the beta and give you feedback in details. Once it is checked for minor modifications, then you may release 1.4.0-stable, where minor changes could follow like usual. 

With this, I want to let you know that I want to join you making a team as a beta tester!

The system of beta testing may give all (future) users confidence that 1.4 is stable and worth looking at. Once they do so, I am sure that people will start to understand the power of  HashtagCMS, which not many have seen in depth until today.

**Comment by marghoobsuleman** [comment]
Hi @ArcDee 
Could you please check now?

How to create multisite instruction. 
https://youtu.be/5YhA0GKRKDg

**Comment by marghoobsuleman** [comment]
Sure Thanks :). Please provide translations. I'll try to make that multilingual. 

> Hello Marghoob,
> 
> After understanding the entire logic of many areas you have poured into your HashtagCMS, I must say that it is well designed. Mentioning again, HashtagCMS is an excellent CMS on Laravel.
> 
> I suggest that you release the HashtagCMS with multi language by default. I can offer translation in German and CMS docs in English, if you want.
> 
> Looking forward to your next version.

**Comment by marghoobsuleman** [comment]
Thank you @ArcDee for taking the time to write and suggestions and going through all the flow. I really appreciate it. Let me come back with an easy solution for this. 
Thanks you so much again.

**Comment by ArcDee** [comment]
The above error is gone after the multisite fix in 1.3.1.

Currently, to receive this fix, one has to change in composer:

"marghoobsuleman/hashtagcms": "dev-master"

Thus, this issue should be closed.
