### ISSUE TITLE
[Feature request] Cloning new sites from a master site (template)

### ISSUE THREAD

**Issue by DeRaja** [marghoobsuleman/hashtagcms#21]
If one wants to create a new site, one has to create it manually. In this process, errors appeared due to manually cloning each elements. This issue is here: [https://github.com/marghoobsuleman/hashtagcms/issues/20](url)

From the experience of the above issue, it would be the best to provide cloning function with one click. Here are my suggestions:

- Provide one master site template in the default installation. For e.g. in table sites_master_template.
- All important values from the master site template cannot be deleted.
- Provide in the master site template by default multiple languages and multiple categories to clone for new site creation, at least two of them.
- The master site template can be extended to contain extra values like new categories, new languages, etc.
- Provide a backup function of the database.

After providing some basic values in a form to create a new site, the master site template will feed default values in all tables in the database and create a new site.

Here are the advantages:

- Cloning function will feed necessary values, including multiple languages and multiple categories etc, with one click.
- The default values in the sites_master_template will not create a Kernel crash.
- Creation of new site will have standard look or layout and menu amongst other sites.
- One can expand languages, categories, etc. into multiple sites with one click.
- Because the scripts are stable and will not create a Kernel crash, the database can be reverted to its old version from a backup, should something go wrong.

Had I had created three languages and ten categories based on master site template, then I could have cloned it - for e.g. - ten new sites with one click instead of going through each area of every new site manually.

With the feature of backup, one could revert the entire database (after newly created site) to it original state manually.

I think this feature request will become a powerful function in the HashtagCMS.

**Comment by marghoobsuleman** [comment]
@DeRaja I've added site clone functionality. Could you please try that in new updates? it's in admin/site -> copy icon just near the Add New button.

**Comment by DeRaja** [comment]
Hello Marghoob,

You are amazingly fast to change the core and pour in such a powerful function into the HashtagCMS. Vowwwwww! 

I looked on these changes you made to 1.3.2 patches. You changed the data loops of each data elements into site elements. I really enjoyed to see those changes. I see your excellent command on Javascripts and php coding. These two talents combined in one person. May be that is the reason why the Laravel core became so powerful, which many have yet to recognize it .

The work is so marvellous. Brilliant!

I updated in my installation of HashtagCMS 1.3.1 (dev-master) to 1.3.2 (dev-master) and got the latest patch. Thereafter, clicking on sites--->Clone sites, I got a blank page with a "Back" link on the top right.

Thereafter, I installed a fresh installation and got everything working in the HashtagCMS.

After login into the dashboard and then clicking on sites--->Clone sites, I got a blank page with a "Back" link on the top right.

In the Laravel.log, I see the following two entries (I emptied it earlier to check):

[xxx] prod.INFO: moduleInfo: {"isSuperAdmin":true,"permission":false}
[xxx] prod.INFO: moduleInfo: {"isSuperAdmin":true,"permission":false}

The first line above was created when I clicked in the dashboard on the Dashboard link.

The second line was generated, when I clicked on sites--->Clone sites.

This means there is something still missing. Permissions may be? There must be something tiny that is missing. Let me know if you want me to check/debug something further. I am looking forward to cloning sites with one click!

**Comment by marghoobsuleman** [comment]
@DeRaja When you are SuperAdmin, you don't need permission. Fresh installation should work. Maybe assets are cached in the browser. To solve that, export config and change 
'version' => env('BE_RESOURCE_VERSION', '311220210430'), to current date. say 
'version' => env('BE_RESOURCE_VERSION', '012520221539')

**Comment by DeRaja** [comment]
Hello Marghoob,

Yes, I substituted this to 011520221539 and that did the trick. Never knew that something like this could happen and could be changed in this manner.

I thought cloning could be used for updates too:

1) Clone mastersite--->newsites
2) Extend config in mastersite (default) like languages, currencies, categories, etc.
3) Update mastersite--->clone manually newsite_one, newsite_two, newsite_three, etc.

I tried it and the MASS CREATING AND - later - UPDATING (with cloning function) works like charm!

With this method, one could configure the basics in master site and apply it to multiple new sites later. After cloning, I could create one more language, currency and apply to all existing sites from the master site.

Cloning function of basic site skeleton from a master site is really a very powerful feature. It will save a lot of time of everyone. I will play with it and let you know if there are problems. Otherwise I will close this issue.

Thanks for this powerful feature.

**Comment by marghoobsuleman** [comment]
Thanks for your time to look into these features. I really appreciate it. :)
I love feedback.

**Comment by DeRaja** [comment]
Hello Marghoob,

When I substituted this to 011520221539 in the fresh installation, it worked. 

I had executed "composer update -W" on cli on my current installation. I did the same in the current installation, i.e. substituted this to 011520221539, and it did not work! Logically the problem was different.

I finally compared both installations and found that "composer update -W" had done ZERO UPDATING! Files app.js, SiteClone.js, logo.png were missing in my current installation. I can repeat this update procedure and found it does not update and install these new (missing) files. I changed in composer.json the version to 1.3.0 (fixed) and made update. It downgraded. Then I changed to 1.3.1 and 1.3.2. IT DID NOT APPLY THE NEW MULTISITE UPDATE WITH CLONING FUNCTION!

When I manually updated these missing files, it worked immediately.

My compare process found that in the current installation, there are files that are not in the fresh install of 1.3.2, like add, etc. that relates to copier function.

I finally deleted the current installation and used fresh installation, changing .env, database.php, etc. specific to the site.

It immediately began to work.

The reason why your trick [env('BE_RESOURCE_VERSION', '011520221539')] worked is due to following reason: This command fired an update in bootstrap/cache/config.php to be generated again. One could also delete config.php manually and that would produce accurate result, giving the system a fresh environment plus all config to boot process NEW in the backend.  One does not (or should not) need to merge array values from hashtagcmsadmin.php. This only gives an extra support.

In my fresh and curennt installation, I have renamed to hashtagcms.phpx and hashtagcmsadmin.phpx. this is no longer necessary. Everything works.

But your trick was very clever to sidetrack the boot process by rewriting config.php.

The conclusion of this problem is:

You are using tags instead of release system. This does confuse composer. 

Better system would be to use release-1.3.2-beta, and then release-1.3.2-stable. Then, using dev-master will update to release-1.3.2-beta and prevent an update on production. With the current method of tagging, the applied patch with stable code will not appear, if it is necessary.

Also, it is common to use #issue-nr. in the changelog and reference issues addressed here. This helps others to click on it and track the discussions, or which issue was handled or fixed.

**Comment by DeRaja** [comment]
Hello Marghoob,

Looking and comparing at the databases, from fresh my current installation, I found that things in them were not in sync. This could be a result of manual cloning for for some other reasons.

The only choice left is to start everything again from fresh.

A learning lesson is that things are getting in chaos internally, when manual work was done. More a script-cloning approach is applied, better is the control and has an immediate impact on user experience and usability.

I will close this issue because the cloning feature has worked in the fresh default installation.

**Comment by DeRaja** [comment]
For anyone having similar problems, try following command:

php artisan vendor:publish

Choose 19 in options.

This will publish from the vendor directory.
