### ISSUE TITLE
[Default route] Non-existant path crashes the Kernel: errorMessage--->"Could not find the category." (Error in calling controller)

### ISSUE THREAD

**Issue by ArcDee** [marghoobsuleman/hashtagcms#22]
Hello Marghoob,

Because HastagCMS uses its own routing, I see that there is no default route defined. It is very easy for any one to crash the Kernel and identify every sensitive detail of the installation.

You can verify this method of making a crash. Just enter any term in the URL of (what you call) category THAT DOES NOT EXISTS to make the Kernel crash. I entered /stories and got following crash error:

``<html><body>

popluated | "Error in calling controller (MarghoobSuleman\\HashtagCms\\Http\\Controllers\\FrontendController@index)"
-- | --
errorMessage | "Could not find the category."

</body>
</html>``

It would be better to have a predefined route in the controller for routing that defaults to the main page like home, should a category or path does not exists.

**Comment by marghoobsuleman** [comment]
This is only available when APP_ENV=local 
Always try to set that in APP_ENV=prod when you are making it live.

**Comment by ArcDee** [comment]
Hi,

Yes. Have to learn a lot about config everywhere. This error disappeared after changing in .env to APP_ENV=prod. Thanks.
