### ISSUE TITLE
[Feature request] Ability to add aliases for combined use of subdomains on multisites and for CDN

### ISSUE THREAD

**Issue by DeRaja** [marghoobsuleman/hashtagcms#23]
Hello,

I have configured two domains: DomainOne.com and DomainTwo.com. However, if I give in the URL www.DomainOne.com and www.DomainTwo.com, I get an error (env=prod):

`"Site has not been set up"`

The adding of aliass of sites like www. is important. Secondly, one could configure subdomains pertaining to a language and parked it on the main domain, as follows:

```
en.DomainOne.com--->/home/xxx/public_html/hashtagcms/public
de.DomainOne.com--->/home/xxx/public_html/hashtagcms/public

en.DomainTwo.com--->/home/xxx/public_html/hashtagcms/public
de.DomainTwo.com--->/home/xxx/public_html/hashtagcms/public
```

Based on the aliases, Laravel + HashtagCMS could fetch respective contents based on site_id and lang_id. currently this is not possible.

**Comment by DeRaja** [comment]
Hi Marghoob,

One possibility would be to enter in the site--->edit a comma separated list of subdomains, like www.DomainOne.com, cdn.DomainOne.com, en.DomainOne.com, de.DomainOne.com, etc. The controller can fetch data from the database, check in the array and query further from site_ids.

IMPORTANT: it must be a list of subdomains for alias to work.

Here, one could also create a new field site_aliases in the database to hold this data for processing of the controller.

**Comment by marghoobsuleman** [comment]
This is supported through config.
